export const MAIN_SEARCH_BY_TEXT = 'MAIN_SEARCH_BY_TEXT'

export const DECREMENT_PAGE = 'DECREMENT_PAGE'
export const INCREMENT_PAGE = 'INCREMENT_PAGE'
export const RESTART_PAGE_NUMBERS = 'RESTART_PAGE_NUMBERS'

export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export const FILTER_BY_COMMUNE = 'FILTER_BY_COMMUNE'
export const FILTER_BY_TAG = 'FILTER_BY_TAG'

export const CLEAR_BODY_SECTION = 'CLEAR_BODY_SECTION'