export const LOGIN_API_REQUEST = 'LOGIN_API_REQUEST';
export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const LOGIN_API_FAILURE = 'LOGIN_API_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
