export const LOGIN_API_REQUEST = 'LOGIN_API_REQUEST';
export const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS';
export const LOGIN_API_FAILURE = 'LOGIN_API_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM';
export const HIDE_LOGIN_FORM = 'HIDE_LOGIN_FORM';

export const SHOW_RESET_PASSWORD_FORM = 'SHOW_RESET_PASSWORD_FORM';
export const HIDE_RESET_PASSWORD_FORM = 'HIDE_RESET_PASSWORD_FORM';

export const RESET_LOGIN_CAPTCHA_CHECK = 'RESET_LOGIN_CAPTCHA_CHECK';
export const LOGIN_CAPTCHA_CHECK_SUCCESS = 'LOGIN_CAPTCHA_CHECK_SUCCESS';
export const LOGIN_CAPTCHA_CHECK_ERROR = 'LOGIN_CAPTCHA_CHECK_ERROR';