export const REQUEST_EVENT = 'REQUEST_EVENT'
export const REQUEST_EVENT_SUCCESS = 'REQUEST_EVENT_SUCCESS'
export const REQUEST_EVENT_FAILURE = 'REQUEST_EVENT_FAILURE'

export const REQUEST_STATICS = 'REQUEST_STATICS_STATICS'
export const REQUEST_STATICS_SUCCESS = 'REQUEST_STATICS_SUCCESS'
export const REQUEST_STATICS_FAILURE = 'REQUEST_STATICS_FAILURE'

export const REQUEST_OBRA = 'REQUEST_OBRA'
export const REQUEST_OBRA_SUCCESS = 'REQUEST_OBRA_SUCCESS'
export const REQUEST_OBRA_FAILURE = 'REQUEST_OBRA_FAILURE'

export const REQUEST_RESULT = 'REQUEST_RESULT'
export const REQUEST_RESULT_SUCCESS = 'REQUEST_RESULT_SUCCESS'
export const REQUEST_RESULT_FAILURE = 'REQUEST_RESULT_FAILURE'

export const REQUEST_ITEM = 'REQUEST_ITEM'
export const REQUEST_ITEM_SUCCESS = 'REQUEST_ITEM_SUCCESS'
export const REQUEST_ITEM_FAILURE = 'REQUEST_ITEM_FAILURE'

export const REQUEST_IMAGES_GALLERY = 'REQUEST_IMAGES_GALLERY'
export const REQUEST_IMAGES_GALLERY_SUCCESS = 'REQUEST_IMAGES_GALLERY_SUCCESS'
export const REQUEST_IMAGES_GALLERY_FAILURE = 'REQUEST_IMAGES_GALLERY_FAILURE'
export const REQUEST_ITEMS_GALLERY = 'REQUEST_ITEMS_GALLERY'
export const REQUEST_ITEMS_GALLERY_SUCCESS = 'REQUEST_ITEMS_GALLERY_SUCCESS'
export const REQUEST_ITEMS_GALLERY_FAILURE = 'REQUEST_ITEMS_GALLERY_FAILURE'

export const REQUEST_CATEGORIES_SECTION = 'REQUEST_CATEGORIES_SECTION'
export const REQUEST_CATEGORIES_SECTION_SUCCESS = 'REQUEST_CATEGORIES_SECTION_SUCCESS'
export const REQUEST_CATEGORIES_SECTION_FAILURE = 'REQUEST_CATEGORIES_SECTION_FAILURE'

export const REQUEST_COMUNAS = 'REQUEST_COMUNAS'
export const REQUEST_COMUNAS_SUCCESS = 'REQUEST_COMUNAS_SUCCESS'
export const REQUEST_COMUNAS_FAILURE = 'REQUEST_COMUNAS_FAILURE'

export const REQUEST_TAGS = 'REQUEST_TAGS'
export const REQUEST_TAGS_SUCCESS = 'REQUEST_TAGS_SUCCESS'
export const REQUEST_TAGS_FAILURE = 'REQUEST_TAGS_FAILURE'

export const REQUEST_CATEGORIAS = 'REQUEST_CATEGORIAS'
export const REQUEST_CATEGORIAS_SUCCESS = 'REQUEST_CATEGORIAS_SUCCESS'
export const REQUEST_CATEGORIAS_FAILURE = 'REQUEST_CATEGORIAS_FAILURE'

export const REQUEST_CONTENT = 'REQUEST_CONTENT'
export const REQUEST_CONTENT_SUCCESS = 'REQUEST_CONTENT_SUCCESS'
export const REQUEST_CONTENT_FAILURE = 'REQUEST_CONTENT_FAILURE'

export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_FAILURE = 'COMMENT_FAILURE'