export const USER_IS_SUBSCRIBED = 'USER_IS_SUBSCRIBED';
export const USER_ISNOT_SUBSCRIBED = 'USER_ISNOT_SUBSCRIBED';

export const REQUEST_SUBSCRIPTIONS = 'REQUEST_SUBSCRIPTIONS'
export const REQUEST_SUBSCRIPTIONS_SUCCESS = 'REQUEST_SUBSCRIPTIONS_SUCCESS'
export const REQUEST_SUBSCRIPTIONS_FAILURE = 'REQUEST_SUBSCRIPTIONS_FAILURE'

export const USER_ISNOT_AUTHENTICATED = 'USER_ISNOT_AUTHENTICATED'