export const USER_ANSWERED_VOTATION = 'USER_ANSWERED_VOTATION'
export const USER_NOT_ANSWERED_VOTATION = 'USER_NOT_ANSWERED_VOTATION'
export const USER_ANSWERED_VOTATION_CHECKED = 'USER_ANSWERED_VOTATION_CHECKED'